name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build containers
      run: docker-compose build

    - name: Run containers
      run: docker-compose up -d

    - name: Wait for containers
      run: sleep 10

    - name: Run API Tests
      run: bash scripts/test.sh

    - name: Stop containers
      run: docker-compose down

